name: "功能建议 / Feature Request"
description: "提出新功能或改进建议 / Propose a new feature or improvement"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        我们欢迎功能建议！请尽可能清晰地描述场景、价值与方案。
        We welcome feature ideas! Please describe use cases, value, and solution clearly.
        
        参考 Contributing / Refer to Contributing:
        - 中文 / Chinese: CONTRIBUTING_zh.md#功能建议
        - English: CONTRIBUTING.md#feature-requests

  - type: checkboxes
    id: prechecks
    attributes:
      label: 预检查 / Pre-checks
      options:
        - label: 我已搜索现有 issues 与 discussions / I have searched existing issues and discussions
          required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题与用例 / Problem Statement & Use Case
      description: 该功能要解决什么问题？在什么场景下使用？/ What problem does it solve and in what context?
      placeholder: 说明痛点与使用场景 / Describe the pain point and use case
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 拟议方案 / Proposed Solution
      description: 简述你期望的行为、交互、配置或 API / Describe expected behavior, interactions, configuration, or API
      placeholder: 你希望如何实现 / How you expect it to work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案 / Alternatives Considered
      description: 你考虑过的其他方式 / Other ways you considered
    validations:
      required: false

  - type: textarea
    id: value
    attributes:
      label: 价值与影响 / Value & Impact
      description: 为什么该功能有价值？影响面与优先级如何？/ Why is it valuable? Scope and priority?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: 其他上下文 / Additional Context
      description: 截图、模型、示例配置等 / Screenshots, mockups, sample config, etc.
    validations:
      required: false

