name: Sync labels

on:
  push:
    branches: [ main ]
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      metadata: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync GitHub labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          # Set to true to remove labels not in the list
          # (keep false initially to avoid surprises)
          prune: false

